spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 1608856332637414
            client-secret: 096877fa6b8bb3ed9700e4ae9ec17c51
            scope:
              - email
              - public_profile
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    generate-ddl: true
  datasource:
    url: jdbc:mysql://localhost:3306/nab
    username: root
    password: root
    initialization-mode: always
    driver-class-name: com.mysql.jdbc.Driver
authen:
  secretKey: FigXRDmiMo2RBtzgTdydkLElfwwWVWe5dsBPIGhUEZRlbkSCwOtCbjCODOpfo7tUJB6L3vEI3hrHVBknR_323AJiZ1O_-688oGp0Vwo-KBSGs-qYGs7a4t4UjcDgQuoByepCzjj01RNbzm9hTskawuweKEGzpHEXsVXRW2qWnls
  expirationTime: 1800  # second
